2025-06-01T13:50:48.8718835Z TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: ubuntu-dev
2025-06-01T13:50:48.9118835Z TRACE:: Engine.Main(): Started 1:50 PM
2025-06-01T13:50:48.9167740Z TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
2025-06-01T13:50:48.9346592Z TRACE:: JobQueue.NextJob(): Selected /LeanCLI/main.py
2025-06-01T13:50:48.9628573Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
2025-06-01T13:50:48.9628858Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
2025-06-01T13:50:48.9628941Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
2025-06-01T13:50:48.9641654Z TRACE:: Config.GetValue(): storage-limit - Using default value: 10737418240
2025-06-01T13:50:48.9641942Z TRACE:: Config.GetValue(): storage-permissions - Using default value: 3
2025-06-01T13:50:48.9642342Z TRACE:: Config.Get(): Configuration key not found. Key: optimization-id - Using default value: 
2025-06-01T13:50:48.9642413Z TRACE:: Config.Get(): Configuration key not found. Key: backtest-name - Using default value: local
2025-06-01T13:50:48.9670102Z TRACE:: Config.Get(): Configuration key not found. Key: data-channel - Using default value: 
2025-06-01T13:50:48.9671255Z TRACE:: Config.Get(): Configuration key not found. Key: python-venv - Using default value: 
2025-06-01T13:50:48.9671719Z TRACE:: Config.Get(): Configuration key not found. Key: out-of-sample-max-end-date - Using default value: 
2025-06-01T13:50:48.9671804Z TRACE:: Config.GetValue(): out-of-sample-days - Using default value: 0
2025-06-01T13:50:48.9677411Z TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
2025-06-01T13:50:48.9677522Z TRACE:: Config.Get(): Configuration key not found. Key: data-monitor - Using default value: QuantConnect.Data.DataMonitor
2025-06-01T13:50:48.9760523Z TRACE:: Config.GetValue(): algorithm-creation-timeout - Using default value: 90
2025-06-01T13:50:48.9823633Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2025-06-01T13:50:48.9829862Z TRACE:: Config.Get(): Configuration key not found. Key: fundamental-data-provider - Using default value: CoarseFundamentalDataProvider
2025-06-01T13:50:48.9842244Z TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
2025-06-01T13:50:48.9844968Z TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
2025-06-01T13:50:48.9879040Z TRACE:: Config.GetValue(): downloader-data-update-period - Using default value: 7
2025-06-01T13:50:48.9885911Z TRACE:: Engine.Run(): Resource limits '0' CPUs. 2147483647 MB RAM.
2025-06-01T13:50:48.9888932Z TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
2025-06-01T13:50:49.4519572Z TRACE:: PythonInitializer.Initialize(): start...
2025-06-01T13:50:50.0190747Z TRACE:: PythonInitializer.Initialize(): ended
2025-06-01T13:50:50.0199924Z TRACE:: AlgorithmPythonWrapper(): Python version 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 21:14:50) [GCC 12.3.0]: Importing python module main
2025-06-01T13:50:51.7158712Z TRACE:: AlgorithmPythonWrapper(): main successfully imported.
2025-06-01T13:50:51.7216140Z TRACE:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
2025-06-01T13:50:51.7292587Z TRACE:: Config.Get(): Configuration key not found. Key: databases-refresh-period - Using default value: 1.00:00:00
2025-06-01T13:50:51.8061514Z TRACE:: Config.GetValue(): mute-python-library-logging - Using default value: True
2025-06-01T13:50:51.8085899Z TRACE:: LocalObjectStore.Initialize(): Storage Root: /Storage. StorageFileCount 9999999. StorageLimit 10240MB
2025-06-01T13:50:51.8123104Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2025-06-01T13:50:51.8150449Z TRACE:: HistoryProviderManager.Initialize(): history providers [SubscriptionDataReaderHistoryProvider]
2025-06-01T13:50:51.8172919Z TRACE:: BaseSetupHandler.Setup(LocalPlatform): UID: 357130, PID: -1, Version: 2.5.0.0, Source: WebIDE
2025-06-01T13:50:51.8190778Z TRACE:: Config.Get(): Configuration key not found. Key: security-data-feeds - Using default value: 
2025-06-01T13:50:51.8302443Z TRACE:: BacktestingResultHandler(): Sample Period Set: 1840.68
2025-06-01T13:50:51.8305730Z TRACE:: Config.GetValue(): forward-console-messages - Using default value: True
2025-06-01T13:50:51.8556465Z ERROR:: Engine.Run(): During the algorithm initialization, the following exception has occurred: error return without exception set
  at Initialize
    self.securities = {}
    ^^^^^^^^^^^^^^^
 in main.py: line 42
 error return without exception set
2025-06-01T13:50:51.8559768Z TRACE:: JOB HANDLERS:
         DataFeed:             QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed
         Setup:                QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler
         RealTime:             QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler
         Results:              QuantConnect.Lean.Engine.Results.BacktestingResultHandler
         Transactions:         QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler
         Object Store:         QuantConnect.Lean.Engine.Storage.LocalObjectStore
         History Provider:     QuantConnect.Lean.Engine.HistoricalData.HistoryProviderManager
         Brokerage:            QuantConnect.Brokerages.Backtesting.BacktestingBrokerage
         Data Provider:        QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider

2025-06-01T13:50:51.8562364Z TRACE:: FileSystemDataFeed.Exit(): Start. Setting cancellation token...
2025-06-01T13:50:51.8568670Z TRACE:: FileSystemDataFeed.Exit(): Exit Finished.
2025-06-01T13:50:51.8570405Z TRACE:: BacktestingResultHandler.Exit(): starting...
2025-06-01T13:50:51.8623920Z TRACE:: BacktestingResultHandler.Exit(): Saving logs...
2025-06-01T13:50:51.8632911Z TRACE:: StopSafely(): Waiting for 'Result Thread' thread to stop...
2025-06-01T13:50:51.8633347Z ERROR:: During the algorithm initialization, the following exception has occurred: error return without exception set
  at Initialize
    self.securities = {}
    ^^^^^^^^^^^^^^^
 in main.py: line 42
 error return without exception set
 error return without exception set
  at Initialize
    self.securities = {}
    ^^^^^^^^^^^^^^^
 in main.py: line 42
 error return without exception set
2025-06-01T13:50:51.8633696Z TRACE:: Debug: Your log was successfully created and can be retrieved from: /Results/1558402356-log.txt
2025-06-01T13:50:51.8633743Z TRACE:: BacktestingResultHandler.Run(): Ending Thread...
2025-06-01T13:50:51.9191234Z TRACE:: 
STATISTICS:: OrderListHash d41d8cd98f00b204e9800998ecf8427e
2025-06-01T13:50:51.9191423Z TRACE:: BacktestingResultHandler.SendAnalysisResult(): Processed final packet
2025-06-01T13:50:51.9194097Z TRACE:: Engine.Run(): Disconnecting from brokerage...
2025-06-01T13:50:51.9194771Z TRACE:: Engine.Run(): Disposing of setup handler...
2025-06-01T13:50:51.9194944Z TRACE:: Engine.Main(): Analysis Completed and Results Posted.
2025-06-01T13:50:51.9220083Z TRACE:: Engine.Main(): Packet removed from queue: 1558402356
2025-06-01T13:50:51.9220689Z TRACE:: LeanEngineSystemHandlers.Dispose(): start...
2025-06-01T13:50:51.9224028Z TRACE:: LeanEngineSystemHandlers.Dispose(): Disposed of system handlers.
2025-06-01T13:50:51.9225040Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): start...
2025-06-01T13:50:51.9228407Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): Disposed of algorithm handlers.
