2025-05-30T21:13:40.5328946Z TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: ubuntu-dev
2025-05-30T21:13:40.5366411Z TRACE:: Engine.Main(): Started 9:13 PM
2025-05-30T21:13:40.5390459Z TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
2025-05-30T21:13:40.5549026Z TRACE:: JobQueue.NextJob(): Selected /LeanCLI/main.py
2025-05-30T21:13:40.5804719Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
2025-05-30T21:13:40.5804965Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
2025-05-30T21:13:40.5805046Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
2025-05-30T21:13:40.5809055Z TRACE:: Config.GetValue(): storage-limit - Using default value: 10737418240
2025-05-30T21:13:40.5809218Z TRACE:: Config.GetValue(): storage-permissions - Using default value: 3
2025-05-30T21:13:40.5809573Z TRACE:: Config.Get(): Configuration key not found. Key: optimization-id - Using default value: 
2025-05-30T21:13:40.5809641Z TRACE:: Config.Get(): Configuration key not found. Key: backtest-name - Using default value: local
2025-05-30T21:13:40.5833024Z TRACE:: Config.Get(): Configuration key not found. Key: data-channel - Using default value: 
2025-05-30T21:13:40.5834008Z TRACE:: Config.Get(): Configuration key not found. Key: python-venv - Using default value: 
2025-05-30T21:13:40.5834517Z TRACE:: Config.Get(): Configuration key not found. Key: out-of-sample-max-end-date - Using default value: 
2025-05-30T21:13:40.5834594Z TRACE:: Config.GetValue(): out-of-sample-days - Using default value: 0
2025-05-30T21:13:40.5839727Z TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
2025-05-30T21:13:40.5839822Z TRACE:: Config.Get(): Configuration key not found. Key: data-monitor - Using default value: QuantConnect.Data.DataMonitor
2025-05-30T21:13:40.5919761Z TRACE:: Config.GetValue(): algorithm-creation-timeout - Using default value: 90
2025-05-30T21:13:40.5981061Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2025-05-30T21:13:40.5986878Z TRACE:: Config.Get(): Configuration key not found. Key: fundamental-data-provider - Using default value: CoarseFundamentalDataProvider
2025-05-30T21:13:40.5998493Z TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
2025-05-30T21:13:40.6001161Z TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
2025-05-30T21:13:40.6031538Z TRACE:: Config.GetValue(): downloader-data-update-period - Using default value: 7
2025-05-30T21:13:40.6039201Z TRACE:: Engine.Run(): Resource limits '0' CPUs. 2147483647 MB RAM.
2025-05-30T21:13:40.6041962Z TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
2025-05-30T21:13:40.9940153Z TRACE:: PythonInitializer.Initialize(): start...
2025-05-30T21:13:41.6105212Z TRACE:: PythonInitializer.Initialize(): ended
2025-05-30T21:13:41.6114785Z TRACE:: AlgorithmPythonWrapper(): Python version 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 21:14:50) [GCC 12.3.0]: Importing python module main
2025-05-30T21:13:43.2042767Z TRACE:: AlgorithmPythonWrapper(): main successfully imported.
2025-05-30T21:13:43.2088150Z TRACE:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
2025-05-30T21:13:43.2161957Z TRACE:: Config.Get(): Configuration key not found. Key: databases-refresh-period - Using default value: 1.00:00:00
2025-05-30T21:13:43.2902295Z TRACE:: Config.GetValue(): mute-python-library-logging - Using default value: True
2025-05-30T21:13:43.2924137Z TRACE:: LocalObjectStore.Initialize(): Storage Root: /Storage. StorageFileCount 9999999. StorageLimit 10240MB
2025-05-30T21:13:43.2959697Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2025-05-30T21:13:43.2985677Z TRACE:: HistoryProviderManager.Initialize(): history providers [SubscriptionDataReaderHistoryProvider]
2025-05-30T21:13:43.3005764Z TRACE:: BaseSetupHandler.Setup(LocalPlatform): UID: 357130, PID: -1, Version: 2.5.0.0, Source: WebIDE
2025-05-30T21:13:43.3023569Z TRACE:: Config.Get(): Configuration key not found. Key: security-data-feeds - Using default value: 
2025-05-30T21:13:43.3111525Z TRACE:: BacktestingResultHandler(): Sample Period Set: 525.96
2025-05-30T21:13:43.3121387Z TRACE:: Config.GetValue(): forward-console-messages - Using default value: True
2025-05-30T21:13:43.3374941Z ERROR:: Engine.Run(): During the algorithm initialization, the following exception has occurred: error return without exception set
  at Initialize
    self.securities = {}
    ^^^^^^^^^^^^^^^
 in main.py: line 12
 error return without exception set
2025-05-30T21:13:43.3377823Z TRACE:: JOB HANDLERS:
         DataFeed:             QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed
         Setup:                QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler
         RealTime:             QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler
         Results:              QuantConnect.Lean.Engine.Results.BacktestingResultHandler
         Transactions:         QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler
         Object Store:         QuantConnect.Lean.Engine.Storage.LocalObjectStore
         History Provider:     QuantConnect.Lean.Engine.HistoricalData.HistoryProviderManager
         Brokerage:            QuantConnect.Brokerages.Backtesting.BacktestingBrokerage
         Data Provider:        QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider

2025-05-30T21:13:43.3380064Z TRACE:: FileSystemDataFeed.Exit(): Start. Setting cancellation token...
2025-05-30T21:13:43.3386378Z TRACE:: FileSystemDataFeed.Exit(): Exit Finished.
2025-05-30T21:13:43.3387879Z TRACE:: BacktestingResultHandler.Exit(): starting...
2025-05-30T21:13:43.3443582Z TRACE:: BacktestingResultHandler.Exit(): Saving logs...
2025-05-30T21:13:43.3453034Z ERROR:: During the algorithm initialization, the following exception has occurred: error return without exception set
  at Initialize
    self.securities = {}
    ^^^^^^^^^^^^^^^
 in main.py: line 12
 error return without exception set
 error return without exception set
  at Initialize
    self.securities = {}
    ^^^^^^^^^^^^^^^
 in main.py: line 12
 error return without exception set
2025-05-30T21:13:43.3453139Z TRACE:: StopSafely(): Waiting for 'Result Thread' thread to stop...
2025-05-30T21:13:43.3453384Z TRACE:: Debug: Your log was successfully created and can be retrieved from: /Results/1422374317-log.txt
2025-05-30T21:13:43.3453429Z TRACE:: BacktestingResultHandler.Run(): Ending Thread...
2025-05-30T21:13:43.3976358Z TRACE:: 
STATISTICS:: OrderListHash d41d8cd98f00b204e9800998ecf8427e
2025-05-30T21:13:43.3976495Z TRACE:: BacktestingResultHandler.SendAnalysisResult(): Processed final packet
2025-05-30T21:13:43.3977835Z TRACE:: Engine.Run(): Disconnecting from brokerage...
2025-05-30T21:13:43.3978097Z TRACE:: Engine.Run(): Disposing of setup handler...
2025-05-30T21:13:43.3978216Z TRACE:: Engine.Main(): Analysis Completed and Results Posted.
2025-05-30T21:13:43.4000200Z TRACE:: Engine.Main(): Packet removed from queue: 1422374317
2025-05-30T21:13:43.4000665Z TRACE:: LeanEngineSystemHandlers.Dispose(): start...
2025-05-30T21:13:43.4003599Z TRACE:: LeanEngineSystemHandlers.Dispose(): Disposed of system handlers.
2025-05-30T21:13:43.4004550Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): start...
2025-05-30T21:13:43.4007827Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): Disposed of algorithm handlers.
